---
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
  - 'plugin:jsx-a11y/recommended'
  - prettier
  - prettier/react
plugins:
  - react
  - import
  - jsx-a11y
settings:
  react:
    version: detect
rules:
  react/prop-types: 0
  react/react-in-jsx-scope: 'off'
  lines-between-class-members:
    - error
    - always
  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - const
        - let
        - var
      next: '*'
    - blankLine: always
      prev:
        - const
        - let
        - var
      next:
        - const
        - let
        - var
    - blankLine: always
      prev: directive
      next: '*'
    - blankLine: any
      prev: directive
      next: directive
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  es6: true
  browser: true
  node: true
globals:
  graphql: false
