---
extends:
  - 'airbnb-base'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/typescript'
  - 'plugin:import/warnings'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
  - 'prettier/react'
plugins:
  - '@typescript-eslint'
  - 'import'
  - 'jsx-a11y'
  - 'react'
settings:
  react:
    version: detect
rules:
  import/extensions: 0
  lines-between-class-members:
    - error
    - always
  prettier/prettier: 'error'
  react/prop-types: 0
  react/react-in-jsx-scope: 'off'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  es6: true
  browser: true
  node: true
globals:
  graphql: false
