nodeLinker: node-modules

npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: ${FA_PRO_NPM_TOKEN}

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com
    npmAlwaysAuth: true
    npmAuthToken: ${FA_PRO_NPM_TOKEN}

yarnPath: .yarn/releases/yarn-2.3.3.cjs
