# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches-ignore: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g gatsby-cli yarn rimraf
      - run: yarn install
        env:
          FA_PRO_NPM_TOKEN: ${{ secrets.FA_PRO_NPM_TOKEN }}
      - run: yarn build
        env:
          GATSBY_ALGOLIA_ADMIN_API_KEY: ${{ secrets.GATSBY_ALGOLIA_ADMIN_API_KEY }}
          GATSBY_ALGOLIA_APPLICATION_ID: ${{ secrets.GATSBY_ALGOLIA_APPLICATION_ID }}
          GATSBY_ALGOLIA_SEARCH_ONLY_API_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_ONLY_API_KEY }}
          FA_PRO_NPM_TOKEN: ${{ secrets.FA_PRO_NPM_TOKEN }}
      - run: git config --global user.email "${{ secrets.GH_EMAIL }}"
      - run: git config --global user.name "${{ secrets.GH_NAME }}"
      - run: npx relative-ci-agent
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
