# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g gatsby-cli yarn
    - run: yarn install
      env:
        FA_PRO_NPM_TOKEN: ${{ secrets.FA_PRO_NPM_TOKEN }}
    - run: yarn build
      env:
        ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        ALGOLIA_SEARCH_ONLY_API_KEY: ${{ secrets.ALGOLIA_SEARCH_ONLY_API_KEY }}
        FA_PRO_NPM_TOKEN: ${{ secrets.FA_PRO_NPM_TOKEN }}
    - run: git config --global user.email "${{ secrets.GH_EMAIL }}"
    - run: git config --global user.name "${{ secrets.GH_NAME }}"
    - run: npx gh-pages -d public -r https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/crfroehlich/blog.git
    - run: npx relative-ci-agent
      env:
        RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}